In [1]:
#standard libraries
import pandas as pd
import numpy as np
from cleantext import clean

In [2]:
file1=pd.read_csv('../dataset files/zomato.csv')
file2=pd.read_csv('../dataset files/Swiggy Bangalore.csv')

In [3]:
file1

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51712,https://www.zomato.com/bangalore/best-brews-fo...,"Four Points by Sheraton Bengaluru, 43/3, White...",Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,080 40301477,Whitefield,Bar,NaN,Continental,"1,500","[('Rated 5.0', ""RATED\n Food and service are ...",[],Pubs and bars,Whitefield
51713,https://www.zomato.com/bangalore/vinod-bar-and...,"Number 10, Garudachar Palya, Mahadevapura, Whi...",Vinod Bar And Restaurant,No,No,NaN,0,+91 8197675843,Whitefield,Bar,NaN,Finger Food,600,[],[],Pubs and bars,Whitefield
51714,https://www.zomato.com/bangalore/plunge-sherat...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,NaN,Whitefield,Bar,NaN,Finger Food,"2,000",[],[],Pubs and bars,Whitefield
51715,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500","[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield
51716,https://www.zomato.com/bangalore/the-nest-the-...,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,No,No,3.4 /5,13,+91 8071117272,"ITPL Main Road, Whitefield","Bar, Casual Dining",NaN,"Finger Food, North Indian, Continental","1,500","[('Rated 5.0', 'RATED\n Great ambience , look...",[],Pubs and bars,Whitefield

In [4]:
file1.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [5]:
file2.columns

Index(['Restaurant Name', 'Category', 'Rating', 'Cost for Two (in Rupees)',
       'Area', 'Offer', 'URL'],
      dtype='object')

In [6]:
file2=file2.rename(columns={'Restaurant Name':'name','Category':'rest_type','Rating':'rate','Cost for Two (in Rupees)':'approx_cost(for two people)',
                     'Area':'location','URL':'url'})

In [7]:
df = file1.append(file2, ignore_index=True)

In [8]:
df.reset_index(drop=True)
df

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city),Offer
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775.0,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,NaN
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787.0,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,NaN
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918.0,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,NaN
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88.0,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,NaN
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166.0,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62009,https://www.swiggy.com/restaurants/holy-chic-y...,NaN,Holy Chic,NaN,NaN,NaN,NaN,NaN,Yeshwanthpur,Continental,NaN,NaN,700,NaN,NaN,NaN,NaN,NaN
62010,https://www.swiggy.com/restaurants/papa-rolls-...,NaN,PAPA ROLLS,NaN,NaN,NaN,NaN,NaN,Yeshwanthpur,"North Indian, Chinese",NaN,NaN,150,NaN,NaN,NaN,NaN,NaN
62011,https://www.swiggy.com/restaurants/rice-sambar...,NaN,RICE SAMBAR,NaN,NaN,NaN,NaN,NaN,Yeshwanthpur,"South Indian, Chinese",NaN,NaN,400,NaN,NaN,NaN,NaN,NaN
62012,https://www.swiggy.com/restaurants/paris-famil...,NaN,Paris Family Restaurant,NaN,NaN,3.6,NaN,NaN,Yeshwanthpur,"Chinese, South Indian, Desserts, Fast Food, Ke...",NaN,NaN,400,NaN,NaN,NaN,NaN,NaN
62013,https://www.swiggy.com/restaurants/swarnas-ati...,NaN,Swarna's Atil,NaN,NaN,NaN,NaN,NaN,Yeshwanthpur,"Indian, Combo, Beverages",NaN,NaN,350,NaN,NaN,NaN,NaN,NaN

In [9]:
df=df.rename(columns={'approx_cost(for two people)':'cost','listed_in(type)':'type','listed_in(city)':'city'})
df

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost,reviews_list,menu_item,type,city,Offer
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775.0,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,NaN
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787.0,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,NaN
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918.0,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,NaN
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88.0,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,NaN
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166.0,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62009,https://www.swiggy.com/restaurants/holy-chic-y...,NaN,Holy Chic,NaN,NaN,NaN,NaN,NaN,Yeshwanthpur,Continental,NaN,NaN,700,NaN,NaN,NaN,NaN,NaN
62010,https://www.swiggy.com/restaurants/papa-rolls-...,NaN,PAPA ROLLS,NaN,NaN,NaN,NaN,NaN,Yeshwanthpur,"North Indian, Chinese",NaN,NaN,150,NaN,NaN,NaN,NaN,NaN
62011,https://www.swiggy.com/restaurants/rice-sambar...,NaN,RICE SAMBAR,NaN,NaN,NaN,NaN,NaN,Yeshwanthpur,"South Indian, Chinese",NaN,NaN,400,NaN,NaN,NaN,NaN,NaN
62012,https://www.swiggy.com/restaurants/paris-famil...,NaN,Paris Family Restaurant,NaN,NaN,3.6,NaN,NaN,Yeshwanthpur,"Chinese, South Indian, Desserts, Fast Food, Ke...",NaN,NaN,400,NaN,NaN,NaN,NaN,NaN
62013,https://www.swiggy.com/restaurants/swarnas-ati...,NaN,Swarna's Atil,NaN,NaN,NaN,NaN,NaN,Yeshwanthpur,"Indian, Combo, Beverages",NaN,NaN,350,NaN,NaN,NaN,NaN,NaN

In [10]:
df=df.drop(['Offer'],axis=1)
df=df.drop(['city'],axis=1)
df=df.drop(['menu_item'],axis=1)

I am not going to drop the columns except for offer column as they will be come in handy in the final product. The offer is an inclusive thing which the restaurants decide depending on the season. I will clean rate column, votes column, cost column as they are numerical columns. 

**Another important thing is to clean categorical columns such as address, online order, book table, rest type, dishes liked, cuisines, review list, menu item. I am going to use Text Summarize and Tensorflow Vector Detection**

In [11]:
df['address'].fillna('Sorry! The adress you are looking for is not found.', inplace=True )
df['online_order'].fillna('No', inplace=True)
df['book_table'].fillna('No',inplace=True)
df['phone'].fillna('Sorry! Phone Number Not Available.', inplace=True)
df['votes'].fillna(0,inplace=True)
df['dish_liked'].fillna('This data is not available', inplace=True)
df['cuisines'].fillna(df['rest_type'],inplace=True)
df['reviews_list'].fillna('The Review for this restaurant is not avialable.',inplace=True)
df['type'].fillna('unknown',inplace=True)

In [12]:
def convert_rate(value):
    if(value=='NEW' or value=='-'):
        return np.nan
    else:
        value=str(value).split('/')
        value=value[0]
        return float(value)
df['rate']=df['rate'].apply(convert_rate)
df.fillna(0, inplace=True)
df

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost,reviews_list,type
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1,775.0,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",Buffet
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1,787.0,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",Buffet
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8,918.0,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",Buffet
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7,88.0,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",Buffet
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8,166.0,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",Buffet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62009,https://www.swiggy.com/restaurants/holy-chic-y...,Sorry! The adress you are looking for is not f...,Holy Chic,No,No,0.0,0.0,Sorry! Phone Number Not Available.,Yeshwanthpur,Continental,This data is not available,Continental,700,The Review for this restaurant is not avialable.,unknown
62010,https://www.swiggy.com/restaurants/papa-rolls-...,Sorry! The adress you are looking for is not f...,PAPA ROLLS,No,No,0.0,0.0,Sorry! Phone Number Not Available.,Yeshwanthpur,"North Indian, Chinese",This data is not available,"North Indian, Chinese",150,The Review for this restaurant is not avialable.,unknown
62011,https://www.swiggy.com/restaurants/rice-sambar...,Sorry! The adress you are looking for is not f...,RICE SAMBAR,No,No,0.0,0.0,Sorry! Phone Number Not Available.,Yeshwanthpur,"South Indian, Chinese",This data is not available,"South Indian, Chinese",400,The Review for this restaurant is not avialable.,unknown
62012,https://www.swiggy.com/restaurants/paris-famil...,Sorry! The adress you are looking for is not f...,Paris Family Restaurant,No,No,3.6,0.0,Sorry! Phone Number Not Available.,Yeshwanthpur,"Chinese, South Indian, Desserts, Fast Food, Ke...",This data is not available,"Chinese, South Indian, Desserts, Fast Food, Ke...",400,The Review for this restaurant is not avialable.,unknown
62013,https://www.swiggy.com/restaurants/swarnas-ati...,Sorry! The adress you are looking for is not f...,Swarna's Atil,No,No,0.0,0.0,Sorry! Phone Number Not Available.,Yeshwanthpur,"Indian, Combo, Beverages",This data is not available,"Indian, Combo, Beverages",350,The Review for this restaurant is not avialable.,unknown

In [13]:
def make_integer(value):
    value=str(value)
    if ',' in value:
        value= value.replace(',','')
        return int(value)
    else:
        return int(value)
df['cost']=df['cost'].apply(make_integer)
df['cost'].unique()

array([ 800,  300,  600,  700,  550,  500,  450,  650,  400,  900,  200,
        750,  150,  850,  100, 1200,  350,  250,  950, 1000, 1500, 1300,
        199,   80, 1100,  160, 1600,  230,  130,   50,  190, 1700,    0,
       1400,  180, 1350, 2200, 2000, 1800, 1900,  330, 2500, 2100, 3000,
       2800, 3400,   40, 1250, 3500, 4000, 2400, 2600,  120, 1450,  469,
         70, 3200,   60,  560,  240,  360, 6000, 1050, 2300, 4100, 5000,
       3700, 1650, 2700, 4500,  140,  220,  399,  438,   99,  249,  380,
        299,  260,  280,  354,  125,  483,  198,  325,  320,   90,  170,
        490,  270,  559,  149,  126,  390,  480,  210,    1,  159,  239,
        251,  110,  138,  310,  499,  275,   10,    2,  238,   20,  298,
        378,  999,  290,  760,  595,  218,   65,  532,  710,  176,  255,
        990,   75,  175,  225,  398,   39,  459,  179,  540,  599,  119,
         30,  158,  349,  798,   15,   89,  355,  182,  203,  178,  148,
        257,  171,  193,  719, 1099,  289,  440,   14,  259,   55,  497,
        899,  163,  248,  799,  295,  224,  385,  590,  703,  347,  363,
        790,  263,  296,  597,  327,  293,  169,  129,  420,  258,  340,
       2022,  104,  370,  699,  301], dtype=int64)

In [14]:
dish_liked=df['dish_liked'].value_counts(ascending=False)
dish_liked
dish_0=dish_liked[dish_liked==28078]
dish_0

Series([], Name: dish_liked, dtype: int64)

In [15]:
def make_other_dish(value):
    if(value in dish_0):
        return 'not rated item'
    else:
        return value
df['dish_liked']=df['dish_liked'].apply(make_other_dish)
df['dish_liked'].value_counts()

This data is not available                                                                           38375
Biryani                                                                                                182
Chicken Biryani                                                                                         73
Friendly Staff                                                                                          69
Waffles                                                                                                 68
                                                                                                     ...
Butter Chicken, Shawarma Roll, Chicken Shawarama, Chicken Grill, Rolls, Al Faham Chicken, Biryani        1
Filter Coffee, Sandwich, Bonda, Vada, Masala Dosa, Salad, Aloo Curry                                     1
Burgers, Fries, Jumbo Royale Burger, Salads, Peri Peri Chicken Salad, Potato Wedges, Rolls               1
Chaat, Pav Bhaji, Raj Kachori, Buttermilk, Ajwaini Paratha, Tawa Pulav, Sev Puri                         1
Paratha, Dal Makhani, Lassi, Naan, Veg Thali, Chole, Kulcha                                              1
Name: dish_liked, Length: 5272, dtype: int64

In [16]:
dish_50=dish_liked[dish_liked<=50]
dish_50

Coffee                                                                                               42
Rooftop Ambience                                                                                     42
Pizza                                                                                                38
Burgers                                                                                              33
Cocktails                                                                                            29
                                                                                                     ..
Butter Chicken, Shawarma Roll, Chicken Shawarama, Chicken Grill, Rolls, Al Faham Chicken, Biryani     1
Filter Coffee, Sandwich, Bonda, Vada, Masala Dosa, Salad, Aloo Curry                                  1
Burgers, Fries, Jumbo Royale Burger, Salads, Peri Peri Chicken Salad, Potato Wedges, Rolls            1
Chaat, Pav Bhaji, Raj Kachori, Buttermilk, Ajwaini Paratha, Tawa Pulav, Sev Puri                      1
Paratha, Dal Makhani, Lassi, Naan, Veg Thali, Chole, Kulcha                                           1
Name: dish_liked, Length: 5265, dtype: int64

In [17]:
for i, element in enumerate(df['reviews_list']):
    df.loc[i,'reviews_list']=clean(df.loc[i,'reviews_list'],fix_unicode=True,to_ascii=True,                  
                                lower=True,                     
                                no_line_breaks=True,           
                                no_urls=True,                 
                                no_emails=True,                
                                no_phone_numbers=True,         
                                no_numbers=True,               
                                no_digits=True,                
                                no_currency_symbols=True,      
                                no_punct=True,                 
                                replace_with_punct="",          
                                replace_with_url="",
                                replace_with_email="",
                                replace_with_phone_number="",
                                replace_with_number="",
                                replace_with_digit="",
                                replace_with_currency_symbol="",
                                lang="en")
df['reviews_list']=df['reviews_list'].str.replace('rated','')
df['reviews_list']=df['reviews_list'].str.replace('\n','')

In [18]:
df

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost,reviews_list,type
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1,775.0,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,a beautiful place to dine inthe interiors ta...,Buffet
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1,787.0,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,had been here for dinner with family turned ...,Buffet
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8,918.0,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,ambience is not that good enough and its not...,Buffet
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7,88.0,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,great food and proper karnataka style full m...,Buffet
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8,166.0,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,very good restaurant in neighbourhood buffet...,Buffet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62009,https://www.swiggy.com/restaurants/holy-chic-y...,Sorry! The adress you are looking for is not f...,Holy Chic,No,No,0.0,0.0,Sorry! Phone Number Not Available.,Yeshwanthpur,Continental,This data is not available,Continental,700,the review for this restaurant is not avialable,unknown
62010,https://www.swiggy.com/restaurants/papa-rolls-...,Sorry! The adress you are looking for is not f...,PAPA ROLLS,No,No,0.0,0.0,Sorry! Phone Number Not Available.,Yeshwanthpur,"North Indian, Chinese",This data is not available,"North Indian, Chinese",150,the review for this restaurant is not avialable,unknown
62011,https://www.swiggy.com/restaurants/rice-sambar...,Sorry! The adress you are looking for is not f...,RICE SAMBAR,No,No,0.0,0.0,Sorry! Phone Number Not Available.,Yeshwanthpur,"South Indian, Chinese",This data is not available,"South Indian, Chinese",400,the review for this restaurant is not avialable,unknown
62012,https://www.swiggy.com/restaurants/paris-famil...,Sorry! The adress you are looking for is not f...,Paris Family Restaurant,No,No,3.6,0.0,Sorry! Phone Number Not Available.,Yeshwanthpur,"Chinese, South Indian, Desserts, Fast Food, Ke...",This data is not available,"Chinese, South Indian, Desserts, Fast Food, Ke...",400,the review for this restaurant is not avialable,unknown
62013,https://www.swiggy.com/restaurants/swarnas-ati...,Sorry! The adress you are looking for is not f...,Swarna's Atil,No,No,0.0,0.0,Sorry! Phone Number Not Available.,Yeshwanthpur,"Indian, Combo, Beverages",This data is not available,"Indian, Combo, Beverages",350,the review for this restaurant is not avialable,unknown

In [28]:
df.to_csv('cleanned_data.csv',index=False)

In [29]:
flie=pd.read_csv('cleanned_data.csv')

In [30]:
flie

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost,reviews_list,type
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1,775.0,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,a beautiful place to dine inthe interiors ta...,Buffet
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1,787.0,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,had been here for dinner with family turned ...,Buffet
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8,918.0,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,ambience is not that good enough and its not...,Buffet
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7,88.0,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,great food and proper karnataka style full m...,Buffet
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8,166.0,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,very good restaurant in neighbourhood buffet...,Buffet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62009,https://www.swiggy.com/restaurants/holy-chic-y...,Sorry! The adress you are looking for is not f...,Holy Chic,No,No,0.0,0.0,Sorry! Phone Number Not Available.,Yeshwanthpur,Continental,This data is not available,Continental,700,the review for this restaurant is not avialable,unknown
62010,https://www.swiggy.com/restaurants/papa-rolls-...,Sorry! The adress you are looking for is not f...,PAPA ROLLS,No,No,0.0,0.0,Sorry! Phone Number Not Available.,Yeshwanthpur,"North Indian, Chinese",This data is not available,"North Indian, Chinese",150,the review for this restaurant is not avialable,unknown
62011,https://www.swiggy.com/restaurants/rice-sambar...,Sorry! The adress you are looking for is not f...,RICE SAMBAR,No,No,0.0,0.0,Sorry! Phone Number Not Available.,Yeshwanthpur,"South Indian, Chinese",This data is not available,"South Indian, Chinese",400,the review for this restaurant is not avialable,unknown
62012,https://www.swiggy.com/restaurants/paris-famil...,Sorry! The adress you are looking for is not f...,Paris Family Restaurant,No,No,3.6,0.0,Sorry! Phone Number Not Available.,Yeshwanthpur,"Chinese, South Indian, Desserts, Fast Food, Ke...",This data is not available,"Chinese, South Indian, Desserts, Fast Food, Ke...",400,the review for this restaurant is not avialable,unknown
62013,https://www.swiggy.com/restaurants/swarnas-ati...,Sorry! The adress you are looking for is not f...,Swarna's Atil,No,No,0.0,0.0,Sorry! Phone Number Not Available.,Yeshwanthpur,"Indian, Combo, Beverages",This data is not available,"Indian, Combo, Beverages",350,the review for this restaurant is not avialable,unknown

In [31]:
location_file=pd.read_csv('locations.csv')
location_file

                               Name                                  geo_loc
0            Bangalore Banashankari        (12.965283249999999, 77.59445195)
1            Bangalore Basavanagudi                 (12.9417261, 77.5755021)
2               Bangalore Jayanagar                 (12.9292731, 77.5824229)
3                Bangalore JP Nagar                 (12.9072515, 77.5782713)
4                     Bangalore BTM  (12.911275849999999, 77.60456543431182)
5       Bangalore Bannerghatta Road                 (12.9521804, 77.6041899)
6         Bangalore Electronic City  (12.848759900000001, 77.64825295827616)
7           Bangalore Sarjapur Road                  (12.920441, 77.6653284)
8            Bangalore Shanti Nagar                 (12.9575547, 77.5979099)
9           Bangalore Richmond Road                 (12.9668257, 77.6096372)
10                    Bangalore HSR                 (12.9092342, 77.6398674)
11  Bangalore Koramangala 7th Block                 (12.9364846, 77.6134783)
12              Bangalore Bellandur                (12.93103185, 77.6782471)
13           Bangalore Marathahalli                 (12.9552572, 77.6984163)
14            Bangalore Indiranagar                 (12.9732913, 77.6404672)
15             Bangalore Whitefield                 (12.9696365, 77.7497448)
16  Bangalore Koramangala 1st Block                 (12.9275886, 77.6308832)
17                Bangalore MG Road                 (12.9755264, 77.6067902)
18          Bangalore Church Street                 (12.9755105, 77.6026774)
19           Bangalore Lavelle Road                 (12.9749487, 77.5997248)
20         Bangalore Residency Road                 (13.0529476, 77.6206061)
21           Bangalore Brigade Road                 (12.9671183, 77.6066149)
22                 Bangalore Ulsoor                 (12.9778793, 77.6246697)
23            Bangalore Frazer Town                  (12.996845, 77.6130165)
24  Bangalore Koramangala 6th Block                 (12.9390255, 77.6238477)
25  Bangalore Koramangala 5th Block                 (12.9348429, 77.6189768)
26            Bangalore Brookefield                 (12.9668213, 77.7168891)
27  Bangalore Koramangala 4th Block                 (12.9327778, 77.6294052)
28              Bangalore Banaswadi                 (13.0141618, 77.6518539)
29           Bangalore Kammanahalli                 (13.0093455, 77.6377094)
30           Bangalore Kalyan Nagar                 (13.0221416, 77.6403368)
31           Bangalore Malleshwaram                 (13.0027353, 77.5703253)
32            Bangalore Rajajinagar                  (12.9882338, 77.554883)
33           Bangalore New BEL Road                  (13.0393922, 77.564105)

In [32]:
location_file[['latitude','longitude']] = location_file.geo_loc.str.split(expand=True)

In [33]:
location_file

,Name,geo_loc,latitude,longitude
0,Bangalore Banashankari,"(12.965283249999999, 77.59445195)","(12.965283249999999,",77.59445195)
1,Bangalore Basavanagudi,"(12.9417261, 77.5755021)","(12.9417261,",77.5755021)
2,Bangalore Jayanagar,"(12.9292731, 77.5824229)","(12.9292731,",77.5824229)
3,Bangalore JP Nagar,"(12.9072515, 77.5782713)","(12.9072515,",77.5782713)
4,Bangalore BTM,"(12.911275849999999, 77.60456543431182)","(12.911275849999999,",77.60456543431182)
5,Bangalore Bannerghatta Road,"(12.9521804, 77.6041899)","(12.9521804,",77.6041899)
6,Bangalore Electronic City,"(12.848759900000001, 77.64825295827616)","(12.848759900000001,",77.64825295827616)
7,Bangalore Sarjapur Road,"(12.920441, 77.6653284)","(12.920441,",77.6653284)
8,Bangalore Shanti Nagar,"(12.9575547, 77.5979099)","(12.9575547,",77.5979099)
9,Bangalore Richmond Road,"(12.9668257, 77.6096372)","(12.9668257,",77.6096372)
10,Bangalore HSR,"(12.9092342, 77.6398674)","(12.9092342,",77.6398674)
11,Bangalore Koramangala 7th Block,"(12.9364846, 77.6134783)","(12.9364846,",77.6134783)
12,Bangalore Bellandur,"(12.93103185, 77.6782471)","(12.93103185,",77.6782471)
13,Bangalore Marathahalli,"(12.9552572, 77.6984163)","(12.9552572,",77.6984163)
14,Bangalore Indiranagar,"(12.9732913, 77.6404672)","(12.9732913,",77.6404672)
15,Bangalore Whitefield,"(12.9696365, 77.7497448)","(12.9696365,",77.7497448)
16,Bangalore Koramangala 1st Block,"(12.9275886, 77.6308832)","(12.9275886,",77.6308832)
17,Bangalore MG Road,"(12.9755264, 77.6067902)","(12.9755264,",77.6067902)
18,Bangalore Church Street,"(12.9755105, 77.6026774)","(12.9755105,",77.6026774)
19,Bangalore Lavelle Road,"(12.9749487, 77.5997248)","(12.9749487,",77.5997248)
20,Bangalore Residency Road,"(13.0529476, 77.6206061)","(13.0529476,",77.6206061)
21,Bangalore Brigade Road,"(12.9671183, 77.6066149)","(12.9671183,",77.6066149)
22,Bangalore Ulsoor,"(12.9778793, 77.6246697)","(12.9778793,",77.6246697)
23,Bangalore Frazer Town,"(12.996845, 77.6130165)","(12.996845,",77.6130165)
24,Bangalore Koramangala 6th Block,"(12.9390255, 77.6238477)","(12.9390255,",77.6238477)
25,Bangalore Koramangala 5th Block,"(12.9348429, 77.6189768)","(12.9348429,",77.6189768)
26,Bangalore Brookefield,"(12.9668213, 77.7168891)","(12.9668213,",77.7168891)
27,Bangalore Koramangala 4th Block,"(12.9327778, 77.6294052)","(12.9327778,",77.6294052)
28,Bangalore Banaswadi,"(13.0141618, 77.6518539)","(13.0141618,",77.6518539)
29,Bangalore Kammanahalli,"(13.0093455, 77.6377094)","(13.0093455,",77.6377094)
30,Bangalore Kalyan Nagar,"(13.0221416, 77.6403368)","(13.0221416,",77.6403368)
31,Bangalore Malleshwaram,"(13.0027353, 77.5703253)","(13.0027353,",77.5703253)
32,Bangalore Rajajinagar,"(12.9882338, 77.554883)","(12.9882338,",77.554883)
33,Bangalore New BEL Road,"(13.0393922, 77.564105)","(13.0393922,",77.564105)

In [34]:
location_file.rename(columns={'Name':'location'})

,location,geo_loc,latitude,longitude
0,Bangalore Banashankari,"(12.965283249999999, 77.59445195)","(12.965283249999999,",77.59445195)
1,Bangalore Basavanagudi,"(12.9417261, 77.5755021)","(12.9417261,",77.5755021)
2,Bangalore Jayanagar,"(12.9292731, 77.5824229)","(12.9292731,",77.5824229)
3,Bangalore JP Nagar,"(12.9072515, 77.5782713)","(12.9072515,",77.5782713)
4,Bangalore BTM,"(12.911275849999999, 77.60456543431182)","(12.911275849999999,",77.60456543431182)
5,Bangalore Bannerghatta Road,"(12.9521804, 77.6041899)","(12.9521804,",77.6041899)
6,Bangalore Electronic City,"(12.848759900000001, 77.64825295827616)","(12.848759900000001,",77.64825295827616)
7,Bangalore Sarjapur Road,"(12.920441, 77.6653284)","(12.920441,",77.6653284)
8,Bangalore Shanti Nagar,"(12.9575547, 77.5979099)","(12.9575547,",77.5979099)
9,Bangalore Richmond Road,"(12.9668257, 77.6096372)","(12.9668257,",77.6096372)
10,Bangalore HSR,"(12.9092342, 77.6398674)","(12.9092342,",77.6398674)
11,Bangalore Koramangala 7th Block,"(12.9364846, 77.6134783)","(12.9364846,",77.6134783)
12,Bangalore Bellandur,"(12.93103185, 77.6782471)","(12.93103185,",77.6782471)
13,Bangalore Marathahalli,"(12.9552572, 77.6984163)","(12.9552572,",77.6984163)
14,Bangalore Indiranagar,"(12.9732913, 77.6404672)","(12.9732913,",77.6404672)
15,Bangalore Whitefield,"(12.9696365, 77.7497448)","(12.9696365,",77.7497448)
16,Bangalore Koramangala 1st Block,"(12.9275886, 77.6308832)","(12.9275886,",77.6308832)
17,Bangalore MG Road,"(12.9755264, 77.6067902)","(12.9755264,",77.6067902)
18,Bangalore Church Street,"(12.9755105, 77.6026774)","(12.9755105,",77.6026774)
19,Bangalore Lavelle Road,"(12.9749487, 77.5997248)","(12.9749487,",77.5997248)
20,Bangalore Residency Road,"(13.0529476, 77.6206061)","(13.0529476,",77.6206061)
21,Bangalore Brigade Road,"(12.9671183, 77.6066149)","(12.9671183,",77.6066149)
22,Bangalore Ulsoor,"(12.9778793, 77.6246697)","(12.9778793,",77.6246697)
23,Bangalore Frazer Town,"(12.996845, 77.6130165)","(12.996845,",77.6130165)
24,Bangalore Koramangala 6th Block,"(12.9390255, 77.6238477)","(12.9390255,",77.6238477)
25,Bangalore Koramangala 5th Block,"(12.9348429, 77.6189768)","(12.9348429,",77.6189768)
26,Bangalore Brookefield,"(12.9668213, 77.7168891)","(12.9668213,",77.7168891)
27,Bangalore Koramangala 4th Block,"(12.9327778, 77.6294052)","(12.9327778,",77.6294052)
28,Bangalore Banaswadi,"(13.0141618, 77.6518539)","(13.0141618,",77.6518539)
29,Bangalore Kammanahalli,"(13.0093455, 77.6377094)","(13.0093455,",77.6377094)
30,Bangalore Kalyan Nagar,"(13.0221416, 77.6403368)","(13.0221416,",77.6403368)
31,Bangalore Malleshwaram,"(13.0027353, 77.5703253)","(13.0027353,",77.5703253)
32,Bangalore Rajajinagar,"(12.9882338, 77.554883)","(12.9882338,",77.554883)
33,Bangalore New BEL Road,"(13.0393922, 77.564105)","(13.0393922,",77.564105)

In [35]:
location_file.to_csv('location.csv',index=False)

In [36]:
flie.to_csv('C:/Users/DELL/Desktop/Restaurant recomendation System/dataset files/cleanned_data.csv')